#include "sos.h"
#include "stm32f4xx_hal.h"

/*
 * NOTE: This is a generic example using the STM32 HAL (Hardware Abstraction
 * Layer). The exact port (e.g., GPIOC) and pin (e.g., GPIO_PIN_13) depend on
 * your specific board.
 * - Blue Pill (STM32F103C8T6) usually has its LED on PC13.
 * - Nucleo boards often have their LED on PA5.
 */

void SystemClock_Config(void);
static void MX_GPIO_Init(void);

int main(void) {
  /* Reset of all peripherals, Initializes the Flash interface and the Systick.
   */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();

  /* Infinite loop */
  while (1) {
    /* Play the SOS pattern on the LED */
    play_sos();
  }
}

/**
 * @brief System Clock Configuration
 * @retval None
 * @note This is usually auto-generated by STM32CubeMX.
 */
void SystemClock_Config(void) {
  /* This implementation is highly specific to the MCU being used.
     Use STM32CubeMX to generate the correct clock configuration for your board.
   */
}

/**
 * @brief GPIO Initialization Function
 * @param None
 * @retval None
 */
static void MX_GPIO_Init(void) {
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable
   * Make sure to enable the clock for the port your LED is on!
   */
  __HAL_RCC_GPIOA_CLK_ENABLE();

  /* Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);

  /* Configure GPIO pin : PA5 */
  GPIO_InitStruct.Pin = GPIO_PIN_5;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

/**
 * @brief This function handles System tick timer.
 *        Without this, HAL_Delay() will freeze forever!
 */
void SysTick_Handler(void) { HAL_IncTick(); }
